Traceback (most recent call last):
  File "runner_hpc.py", line 434, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "runner_hpc.py", line 63, in repeat_exp
    with open("../dump/repeat_margin_" + margin + ".pickle","w") as handle:
TypeError: cannot concatenate 'str' and 'float' objects
Traceback (most recent call last):
  File "runner_hpc.py", line 434, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "runner_hpc.py", line 66, in repeat_exp
    comm.send(results,dest=0)
  File "MPI/Comm.pyx", line 1175, in mpi4py.MPI.Comm.send (src/mpi4py.MPI.c:106424)
  File "MPI/msgpickle.pxi", line 211, in mpi4py.MPI.PyMPI_send (src/mpi4py.MPI.c:42120)
mpi4py.MPI.Exception: Other MPI error, error stack:
MPI_Send(173)..............: MPI_Send(buf=0x363b9a4, count=39651, MPI_BYTE, dest=0, tag=0, MPI_COMM_WORLD) failed
MPID_nem_tcp_connpoll(1826): Communication error with rank 0: Connection refused
Traceback (most recent call last):
  File "runner_hpc.py", line 434, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "runner_hpc.py", line 66, in repeat_exp
    comm.send(results,dest=0)
  File "MPI/Comm.pyx", line 1175, in mpi4py.MPI.Comm.send (src/mpi4py.MPI.c:106424)
  File "MPI/msgpickle.pxi", line 211, in mpi4py.MPI.PyMPI_send (src/mpi4py.MPI.c:42120)
mpi4py.MPI.Exception: Other MPI error, error stack:
MPI_Send(173)..............: MPI_Send(buf=0x41aee64, count=39651, MPI_BYTE, dest=0, tag=0, MPI_COMM_WORLD) failed
MPID_nem_tcp_connpoll(1826): Communication error with rank 0: Connection refused
